#Auth routes

#Sign up

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
        "email": "radu2@gmail.com",
        "password": "123"
}

###

#Sign in

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
        "email": "radu@gmail.com",
        "password": "123"
}

###

#Get current user

GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoicmFkdUBnbWFpbC5jb20iLCJpYXQiOjE2ODI1NDQyMzAsImV4cCI6MTY4MjU0NTEzMH0.TzlOg6XtI2rR3z9bAZmBnvgh-IE5gml7-Sn-bAZ9oRE
