#Auth routes

#Sign up

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
        "email": "radu2@gmail.com",
        "password": "123"
}

###

#Sign in

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
        "email": "radu@gmail.com",
        "password": "123"
}

###

#Get current user

GET http://localhost:3000/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoicmFkdUBnbWFpbC5jb20iLCJpYXQiOjE2ODI1NDU0MzUsImV4cCI6MTY4MjU0NjMzNX0.4NFIauFL7PCZi27L7jPLg_2M7VDTRIqjgHBNIcpZz3Q
